### ISSUE TITLE
CLI fails to execute

### ISSUE THREAD

**Issue by borost1** [i18next/i18next-gettext-converter#124]
Hi,
I am barely used to needing global node modules this much and I am quite stuck.
I have globally installed the package, yet even an `i18next-conv` gives me the following error in the console:
```
/usr/local/lib/node_modules/i18next-conv/bin/index.js:3
import path from 'path';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I have absolutely no clue why it is not working.
My system is:
```
Operating System: Ubuntu 20.04.3 LTS
Kernel: Linux 5.11.0-43-generic
Architecture: x86-64
```
Node version: v10.19.0

It is absolutely possible that I have missed something, yet I tried checking all documentation without success.
Many thanks in advance!

**Comment by adrai** [comment]
https://github.com/i18next/i18next-gettext-converter/releases/tag/v11.0.0
**Support node >= 12**
